#################################################
# Config: Development                           #
#################################################
# (production settings go in _config.build.yml) #

#############
# Meta info #
#############

name: Static Site Example.com
url: 'http://example.com'
description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
timezone: America/Los_Angeles
favicon: /favicon.ico # <-- feel free to change but it should be something
googleanalytics: UA-00000000-1

twitter: foobar
twitterid: 99999999  # Twitter account ID
googleid: 99999999999999999999 # Publisher ID

share:
  image: /path/to/image.jpg
  width: 1200 # Facebook recommends minimum of 1200 x 630
  height: 630
  description: Facebook can get different text from search engines
  title: also share title can be different from search engine/browser title

#############
# Authoring #
#############

future: true
show_drafts: true
permalink: pretty

collections:
  static:
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'

#############
# Compiling #
#############

exclude: ['img']
keep_files: ['img', 'js', 'css']

highlighter: rouge

markdown: kramdown
kramdown:
#  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
