#################################################
# Config: Development                           #
#################################################
# (production settings go in _config.build.yml) #

#############
# Meta info #
#############

name: Static Site Example.com
url: 'http://example.com'
description: I was a developer with Obama for America, building cool things to help get our 44th president re-elected.
timezone: America/Los_Angeles
googleanalytics: UA-00000000-1
author:
  name: Foo Bar
  email: foo@example.com
  github: foobar
  twitter: foobar
  twitterid: 99999999  # Twitter account ID
  googleid: 99999999999999999999 # Publisher ID

#############
# Authoring #
#############

future: true
show_drafts: true
permalink: pretty

collections:
  static:
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
  -
    scope:
      path: 'fingerprints'
    values:
      layout: 'screenshot-post'
      permalink: /:categories/:title/
  -
    scope:
      path: 'words'
    values:
      layout: 'written-post'
      permalink: /words/:year/:month/:title/
  -
    scope:
      path: 'knitting'
    values:
      layout: 'written-post'

#############
# Compiling #
#############

exclude: ['img']
keep_files: ['img', 'js', 'css']

highlighter: rouge

markdown: kramdown
kramdown:
#  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
