---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "We All Js - A JavaScript Community for All of Us"
keywords:    "wealljs, javascript, js, social justice, woc, poc, lgbtq, women in tech, diversity, inclusivity"
description: "We All JS is a JavaScript community centered around inclusion, positive community building, mutual support, and opening up new opportunities. It is an experiment in building communities up in the modern tech industry, with hopes of helping develop processes and tools to make sure people who are usually excluded get to participate openly and comfortably."
source_link: "https://github.com/wealljs/wealljs.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
#google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false
